### ISSUE TITLE
make ci/cd work

### ISSUE THREAD

**Issue by guysoft** [guysoft/pi-imager#2]
The images need to be built for:

* Windows
* Linux (ubuntu and other)
* Mac

**Comment by guysoft** [comment]
There is a working github action that builds the .deb linux version


Note - it might be a good idea to rename the deb pacakge to pi-imager, so you can install both rpi-imager and pi-imgaer alongside

![Screenshot_20220203_012836](https://user-images.githubusercontent.com/325670/152255012-e260a6b1-df25-4928-a8db-4ce92f448fd5.png)

**Comment by kingosticks** [comment]
https://github.com/marketplace/actions/install-qt might be helpful, especially for the Windows side. I didn't realise Github actions had support for Windows environments - cool!

**Comment by kingosticks** [comment]
Also, the github Windows env [comes with MSYS2 already](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#msys2) so should be able to take the easier pre-built SSL option rather than compiling from source, as mentioned [here](https://wiki.qt.io/Compiling_OpenSSL_with_MinGW#Pre-built_packages).

Then there appeared to be [this action](https://github.com/marketplace/actions/makensis) available for the Nullsoft scriptable install system.

Lastly there is https://github.com/dlemstra/code-sign-action but I've zero idea about Windows code signing.

Note, I have never tried any of this! I am not really a Windows person.

**Comment by guysoft** [comment]
I am stuck with OpenSSL not getting detected:
Been bashing against it the past few days and it just wont build from source, and won't take the pre-build binaries
https://github.com/raspberrypi/rpi-imager/issues/351

**Comment by guysoft** [comment]
~~Windows builds now in the ``windows-ci`` branch, and generates ``rpi-imager.exe`` but for some reason when I run it on my VM it also shipps qt5.dll and a bunch of them that it does not ship on github actions, no idea why.~~
```
Error copying file "D:/a/pi-imager/pi-imager/qt/Qt/5.15.2/mingw81_32/lib/cmake/Qt5/../../../bin/libcrypto-1_1.dll" to "D:/a/pi-imager/pi-imager/build/deploy".
```

Got it, it should build soon for windows, unsigned and no installer, but good enough :)

**Comment by guysoft** [comment]
Windows CI/CD works, next one is mac.

**Comment by guysoft** [comment]
Mac builds and signs now. it makes an .app and not a dmg, but good enough for running. Closing for now. Once I get something that is useful it would make sense to reopen or open an issue per OS. An appimage might also make sense, it was requested here: https://github.com/raspberrypi/rpi-imager/issues/350

**Comment by guysoft** [comment]
Released FYI
